name: 'Run msys2-tests'
description: 'Runs msys2-tests'
runs:
  using: 'composite'
  steps:
    - shell: msys2 {0}
      run: |
        . '${{ github.action_path }}/group_helper.sh' "test: toolchain"
        make -C '${{ github.action_path }}' -j toolchain

    - shell: msys2 {0}
      run: |
        . '${{ github.action_path }}/group_helper.sh' "test: rust"
        make -C '${{ github.action_path }}' -j rust

    - shell: msys2 {0}
      run: |
        . '${{ github.action_path }}/group_helper.sh' "test: python"
        make -C '${{ github.action_path }}' -j python

    - shell: msys2 {0}
      run: |
        . '${{ github.action_path }}/group_helper.sh' "test: cmake"
        make -C '${{ github.action_path }}' -j cmake

