name: main

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, prefix:  mingw-w64-x86_64, cc: gcc, cxx: g++, fc: gfortran },
          { msystem: MINGW32, prefix:  mingw-w64-i686, cc: gcc, cxx: g++, fc: gfortran },
          { msystem: UCRT64,  prefix:  mingw-w64-ucrt-x86_64, cc: gcc, cxx: g++, fc: gfortran },
          { msystem: UCRT64,  prefix:  mingw-w64-ucrt-x86_64, cc: clang, cxx: clang++, fc: flang },
          { msystem: CLANG32, prefix:  mingw-w64-clang-i686, cc: clang, cxx: clang++ },
          { msystem: CLANG64, prefix:  mingw-w64-clang-x86_64, cc: clang, cxx: clang++, fc: flang },
          { msystem: MSYS, cc: gcc, cxx: g++, fc: gfortran },
        ]

    name: ${{ matrix.msystem }}-${{ matrix.cc }}
    runs-on: windows-2022
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      FC: ${{ matrix.fc }}
    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.msystem != 'MSYS' && (matrix.msystem != 'UCRT64' || matrix.cc != 'clang') }}
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            ${{ matrix.prefix }}-meson
            ${{ matrix.prefix }}-ninja
            ${{ matrix.prefix }}-cmake
            ${{ matrix.prefix }}-make
            ${{ matrix.prefix }}-omp
            ${{ matrix.prefix }}-fc
            ${{ matrix.prefix }}-${{ matrix.cc }}
            ${{ matrix.prefix }}-rust
            ${{ matrix.prefix }}-python
            ${{ matrix.prefix }}-python-setuptools
            ${{ matrix.prefix }}-autotools
            ${{ matrix.prefix }}-go
            make

      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.msystem == 'UCRT64' && matrix.cc == 'clang' }}
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            ${{ matrix.prefix }}-meson
            ${{ matrix.prefix }}-ninja
            ${{ matrix.prefix }}-cmake
            ${{ matrix.prefix }}-make
            ${{ matrix.prefix }}-openmp
            ${{ matrix.prefix }}-lld
            ${{ matrix.prefix }}-libc++
            ${{ matrix.prefix }}-flang
            ${{ matrix.prefix }}-${{ matrix.cc }}
            ${{ matrix.prefix }}-rust
            ${{ matrix.prefix }}-python
            ${{ matrix.prefix }}-python-setuptools
            ${{ matrix.prefix }}-autotools
            ${{ matrix.prefix }}-go
            make

      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.msystem == 'MSYS' }}
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            meson
            ninja
            cmake
            make
            gcc
            gcc-fortran
            python
            python-setuptools
            autotools

      - name: Add staging repo
        shell: msys2 {0}
        run: |
          sed -i '1s|^|[staging]\nServer = https://repo.msys2.org/staging/\nSigLevel = Never\n|' /etc/pacman.conf

      - name: Update using staging
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'

      - name: Run Tests
        shell: msys2 {0}
        run: |
          make -j
